tasks:
  - name: eks-workspace
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      #!/bin/bash
      set -e

      # Install AWSCLI v2
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      export PATH=/usr/local/bin:$PATH
      source ~/.bash_profile

      # Install kubectl
      sudo curl -o /usr/local/bin/kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.4/2023-08-16/bin/linux/amd64/kubectl
      sudo chmod +x /usr/local/bin/kubectl

      # Install eksctl
      curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      sudo mv -v /tmp/eksctl /usr/local/bin