apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/demo-frontend
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/demo-frontend
    newTag: abcdefg
resources:
  - ../../base
patchesStrategicMerge:
  - frontend-deployment.yaml
  - frontend-service.yaml